development:
  adapter: postgresql
  database: sampleApp
  pool: 5
  username: postgres
  password: Maver1ck


test:
  adapter: postgresql
  database: sampleAppTest
  pool: 5
  username: postgres
  password: Maver1ck
